version: '3'
services:
  backend:
    container_name: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
      - OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=${HONEYCOMB_API_KEY}"
      - OTEL_SERVICE_NAME="express-svc"
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_SERVICE_NAME="react-svc"
  collector:
    container_name: 'collector'
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-config.yaml]
    volumes:
      - ./collector/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
